[project]
name = "django-admin-multi-select-filter"
version = "1.5.0"
description = "Django admin filter for multiple select"
readme = "README.md"
authors = [{ name = "Job Doesburg", email = "job.doesburg@gmail.com" }]
license = { file = "LICENSE" }
requires-python = ">=3"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Framework :: Django",
    "Framework :: Django :: 3.0",
    "Framework :: Django :: 3.1",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
    "Framework :: Django :: 4.1",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]

dependencies = [
    "django>=3",
]

[project.optional-dependencies]
django42 = ["django~=4.2.0"]
django52 = ["django~=5.2.0"]
test = ["pytest", "pytest-django", "factory_boy", "pytest-cov"]

[project.urls]
homepage = "https://github.com/JobDoesburg/django-admin-multi-select-filter"
repository = "https://github.com/JobDoesburg/django-admin-multi-select-filter"
documentation = "https://github.com/JobDoesburg/django-admin-multi-select-filter"

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.html"]

[tool.ruff]
line-length = 119
output-format = "grouped"
show-fixes = true
target-version = "py313"
exclude = [".svn", "CVS", ".bzr", ".hg",".git", "__pycache__", ".tox", ".eggs", "*.egg", ".venv", "env", "venv", "build"]

[tool.ruff.lint]
select = ["W", "E", "F", "I", "N", "DJ", "T20", "Q"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.lint.mccabe]
max-complexity = 6

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.app.settings"
addopts = "-ra -q"
pythonpath =". src"