[tox]
envlist =
    py39-django42
    py310-django{42,52}
    py311-django{42,52}
    py312-django{42,52}
    py313-django52

labels =
    pyproject = pyproject,
    lint = lint,
    format = format,
    py39 = py39-django42
    py310 = py310-django{42,52}
    py311 = py311-django{42,52}
    py312 = py312-django{42,52}
    py313 = py313-django52

[testenv]
setenv =
    PYTHONUTF8 = 1
    REPORT_NAME = {env:TOX_ENV:{envname}}

[testenv:py3{9,10,11,12,13}-django{42,52}]
extras =
    django42: django42
    django52: django52
    test
allowlist_externals =
    coverage
commands =
    pytest \
        --cov django_admin_multi_select_filter \
        --cov-report term-missing \
        --cov-append \
        --junitxml=.reports/{env:REPORT_NAME}_junit.xml \
        {posargs}
commands_post =
    coverage xml -o .reports/{env:REPORT_NAME}_coverage.xml

[testenv:pyproject]
skip_install = true
deps =
    validate-pyproject[all]~=0.12.1
commands =
    validate-pyproject pyproject.toml

[testenv:lint]
skip_install = true
deps =
    ruff~=0.9.0
commands =
    ruff check . --output-format=full

[testenv:format]
skip_install = true
deps =
    ruff~=0.9.0
commands =
    ruff format --diff .
